spring:
  application:
    name: store-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8084}

app:
  payments:
    url: ${PAYMENTS_URL}
    internal-api-key: ${INTERNAL_API_KEY}
  jwt:
    secret: ${JWT_SECRET}